### ISSUE TITLE
Sync VM

### ISSUE THREAD

**Issue by taofineberg** [TheNetworkGuy/netbox-zabbix-sync#17]
I have noticed that this only sync device and not VM's 

Could there be an option to also sync VM's

**Comment by taofineberg** [comment]
Looking into this in more detail 
1)	It would be nice if you could assign a Zabbix template directly on the device and not only on the device type
        a.	Use case would be device type DL 280 server. This could be a windows or Linux install and would require a different template. 
              i.	I have tried this but if there is no template added to the device type it fails , this makes sense as I am sure it is only looking on the device type for the zabbix_template. The workaround would be to make a DL 280-windows , DL 280-linux but this does not seem like a great way forward. 
2)	To add a VM you would also add the custom fields zabbix_hostid and zabbix_template to Virtualization > virtual machine . This way you could allocate a different template 
3)	Adding multiple templates would be usefully but not as much of a big issue as the workaround is make a template and link all of the required templates directly in  Zabbix

**Comment by TheNetworkGuy** [comment]
This project was never intended to synchronize VM's. A couple of reasons but mostly;
 - Personally i've never seen an implementation of Netbox with VM's administrated and actually being used as SOT for other underlying systems
 - I wanted to keep the scope of this project small and only focused on physical devices

I'll look into the options but VM's require a whole different API point, different checks, different custom fields. Basically rewriting a shitload of code. I'm currently very busy in my own time so don't expect the scope of this project to change anytime soon, unless someone else wants to start with the work. At the same time it could be interesting so i won't close the issue either. Just very busy a.t.m. and cannot spend any time with such a big feature request.

**Comment by TheNetworkGuy** [comment]
So i've looked into this and there are (mostly) 2 deal breakers.

- The hostgroup pattern has some variables which VM's do not posses or are not required. For example a manufacturer name. Furthermore now that you can assign a custom field as variable, this custom field needs to be present on 2 different object types.
-  The option of assigning a template to a device type seems logical. It makes sense that 2 devices which are the same type are also using the same type of Zabbix template. However i have no real logical way of defining this data under a VM since there is no device type associated with a VM.

So for right now i will not implement VM sync. This doesn't mean that it will never be implemented but it does mean that other more important issues and enhancements are processed before this.
