### ISSUE TITLE
[idea] Device name (netbox) as visible hostname (zabbix)

### ISSUE THREAD

**Issue by k109x** [TheNetworkGuy/netbox-zabbix-sync#45]
Hi! Great project!
I needed support for long device host name, so and I made a small patch, it might be interesting.
I changed the variable mapping, self.name is now "visible name" field in zabbix:

![image](https://github.com/TheNetworkGuy/netbox-zabbix-sync/assets/52101050/9ee64d90-38fd-48c3-a81f-5d8189f8400a)

createInZabbix:
```
                host = self.zabbix.host.create(host=self.ip,
                                                     name=self.name,
```

zabbixHostnameExists:
```
        host = self.zabbix.host.get(filter={'name': self.ip}, output=[])
```

ConsistencyCheck:
```
        if(host["name"] == self.name):
            logger.debug(f"Device {self.name}: visible name in-sync.")
        else:
            logger.warning(f"Device {self.name}: visible name OUT of sync. "
                           f"Received value: {host['name']}")
            self.updateZabbixHost(name=self.name)
        if(host["host"] == self.ip):
            logger.debug(f"Device {self.name}: hostname in-sync.")
        else:
            logger.warning(f"Device {self.name}: hostname OUT of sync. "
                           f"Received value: {host['host']}")
            self.updateZabbixHost(host=self.ip,name=self.name)
```

**Comment by TheNetworkGuy** [comment]
Glad to hear that you like the project! I used the "host name" field as a starting point given that the "host name" field is mandatory and the "visible name" field is optional. I might implement a simple function that would allow users to set the "visible name" field as preferred instead of the "host name" field.

However since the host name field is mandatory, what would your preference be? A shorter version of the visible name or replace it with the IP address (like you did.)

**Comment by k109x** [comment]
It's clear.. ;) But, look at zabbix docs about hostname field: 
_Alphanumerics, spaces, dots, dashes and underscores are allowed. However, leading and trailing spaces are disallowed._
Device name in netbox can contain any characters. 
Due to this, an error may occur during synchronization

There are two ways: filter device name variable, or change hostname variable mapping to visible name, primary_ip -> hostname
I can also note that "device name" field in netbox is not unique, but "hostname" in zabbix - does.

**Comment by q1x** [comment]
I agree it would be useful to utilize 'visible name' and 'host name' fields separately, as 'host name' is often a technical name and 'visible name' a more user friendly name for the user using the dashboard. 

However, I'm not fond of using the IP address as the 'host name' in Zabbix as that could easily result in naming clashes in multi tenant or multi-vrf environments.

Food for thought?

**Comment by k109x** [comment]
Maybe you're right. 
What about another suggestions? 'host name' can be filled as 'asset tag' value, if it is missing, set 'host name' as "device[netbox_device_id]"

**Comment by TheNetworkGuy** [comment]
The asset tag could be useful, however this is not an option in clustered setup where the name is overwritten by the cluster name. Assuming that you give similar names to clustered devices (eg. long names, umlauts, non-allowed characters.)

Personally i don't see a lot of Netbox deployment utilizing the asset field. However this doesn't mean its not viable. It could provide for an easy "backdoor" trick for long names and special characters.

**Comment by TheNetworkGuy** [comment]
On second thought this might also clash with the requirement of unique hostnames. Given this scenario with 2 switches:


- ........Very long name in Netbox declared which is longer than 128 characters switch01
- ........Very long name in Netbox declared which is longer than 128 characters switch01

Cutting off the last couple of characters would end the string with something like "in Netbox declared which is longer than 128 chara". Therefore making them both identical and failing the hostname unique requirement.

On the other hand starting at the front isn't ideal either since this comes with the same risks.

@k109x Can you elaborate your use case on why you use such long names? If it's just one or 2 hosts within an inventory of a few 100s then i'm more tempted to make a check for the length of a hostname and skip a host if its name is longer than 128 characters.

**Comment by TheNetworkGuy** [comment]
So after some code digging i found the following:

Testing on Netbox 4: it seems that i hit a hard limit of 64 characters for the device name. My fix does seem to work for #42. Looking forward to your reply and use case since i don't see a problem with an enforced 64 character limit in Netbox syncing to a 128 character limit field in Zabbix.

**Comment by k109x** [comment]
@TheNetworkGuy I have this cases:
- The name field in the netbox does not reflect a network name, so device names can be assigned descriptions, either automatically generated hostnames, or the field can be empty.
- the hostname can contains special characters or non-English characters

I use this construct in production:

```
 host = self.zabbix.host.create(name=self.name,
                                               host=f"netbox_device_{self.id}",
                                               status=self.zabbix_state,
                                               interfaces=interfaces,
                                               groups=groups,
                                               templates=self.zbx_templates,
                                               proxy_hostid=self.zbxproxy,
                                               description=f"https://mynetboxhost.domain/dcim/devices/{self.id}/")
```

**Comment by TheNetworkGuy** [comment]
Okay that makes sense. I've updated the code to use the same method as you did but only for "special names" to fix the point that you bring up: "the hostname can contains special characters or non-English characters".

However i am unable to replicate your initial comment about the character limit. Can i conclude that this fix for now is enough for you to close this issue? :)

**Comment by k109x** [comment]
Yes, sure
Thanks a lot
