### ISSUE TITLE
Misleading github topic netbox-plugin

### ISSUE THREAD

**Issue by ryanmerolle** [TheNetworkGuy/netbox-zabbix-sync#9]
It seems your repo does not meet the [definition ](https://netbox.readthedocs.io/en/stable/plugins)of a [netbox-plugin](https://github.com/topics/netbox-plugin) but more of a python script using pynetbox.

This script could be added as a [netbox-plugin](https://github.com/topics/netbox-plugin) if you so wanted.

I do think this is a useful script regardless.

**Comment by TheNetworkGuy** [comment]
Bit of a shame and confusing since i added the tag after a community suggestion: https://github.com/TheNetworkGuy/netbox-zabbix-sync/issues/7. I have no problem removing the tag but i don't quite get your initial message since it contradicts itself (i think):

"Does not meet the definition" and "could be added as netbox-plugin" is kind of the opposite of each other, if you could elaborate a bit more that would be great :)

**Comment by ryanmerolle** [comment]
Sorry for the confusing wording.  There is no strict enforcement of the topic, so I was suggesting if you do wanted you could keep it in the netbox-plugin topic, but it really was not one.

**Comment by TheNetworkGuy** [comment]
Ah i understand. I have no personal preference in this. Indeed it seems a bit overkill to call this a full plugin so i'll remove the tag for now :)
